import {
  AppSettings,
  BadgeItem,
  DailyGoalStatus,
  LayoutConfig,
  QuoteItem,
  RankInfo,
  StreakData,
  SubjectItem,
  UserProfile,
  AdaptivePlannerState
} from './types';

export const APP_MOTTO = 'كل جلسة هادئة تقرّبك من هدفك.';
export const STRICT_RETURN_MESSAGE = 'عاد المرفأ إلى الواجهة. خذ نفسًا عميقًا وأكمل جلستك.';

export const RANKS: RankInfo[] = [
  {
    id: 'rank_1',
    name: 'رفيق الرصيف',
    requiredPoints: 0,
    description: 'بداية الرحلة في مرسى التركيز واستكشاف السواحل المعرفية.',
  },
  {
    id: 'rank_2',
    name: 'بحّار البداية',
    requiredPoints: 5,
    description: 'أكملت 5 ساعات من الجلسات المركزة وأبحرت بثقة.',
  },
  {
    id: 'rank_3',
    name: 'حارس البوصلة',
    requiredPoints: 15,
    description: 'تمتلك وجهة ثابتة ولا تشتتك الرياح العابرة.',
  },
  {
    id: 'rank_4',
    name: 'ملاح التركيز',
    requiredPoints: 30,
    description: 'أتقنت فن الانغماس الكامل والعمل العميق لساعات متواصلة.',
  },
  {
    id: 'rank_5',
    name: 'ربان الإنجاز',
    requiredPoints: 60,
    description: 'بلغت 60 ساعة من الانضباط العالي وحققت أهدافاً طموحة.',
  },
  {
    id: 'rank_6',
    name: 'قائد المرفأ',
    requiredPoints: 100,
    description: 'مائة ساعة من العزم والرسو الراسخ في ميادين المعرفة.',
  },
  {
    id: 'rank_7',
    name: 'سيد الأعماق',
    requiredPoints: 180,
    description: 'تغوص في أدق المسائل دون كلل وبلغت أفق التمكن والرسوخ.',
  },
  {
    id: 'rank_8',
    name: 'أسطورة المرفأ',
    requiredPoints: 365,
    description: 'رتبة شرفية عليا تعادل 365 ساعة دراسة عميقة مكتملة.',
    isHonorary: true,
  },
];

export const INITIAL_BADGES: BadgeItem[] = [
  {
    id: 'b_first_dock',
    name: 'أول رسو',
    description: 'إكمال أول جلسة تركيز بنجاح.',
    condition: 'إكمال جلسة واحدة',
    targetValue: 1,
    currentValue: 0,
    unit: 'جلسة',
    icon: 'Anchor',
    unlocked: false,
    unlockedAt: null,
  },
  {
    id: 'b_time_keeper',
    name: 'حارس الوقت',
    description: 'إكمال 5 ساعات مذاكرة مسجلة في المرفأ.',
    condition: 'إكمال 5 ساعات (300 دقيقة)',
    targetValue: 300,
    currentValue: 0,
    unit: 'دقيقة',
    icon: 'Clock',
    unlocked: false,
    unlockedAt: null,
  },
  {
    id: 'b_start_flame',
    name: 'شعلة البداية',
    description: 'الحفاظ على وتيرة المذاكرة لمدة 3 أيام متتالية مؤهلة.',
    condition: 'ستريك 3 أيام',
    targetValue: 3,
    currentValue: 0,
    unit: 'يوم',
    icon: 'Flame',
    unlocked: false,
    unlockedAt: null,
  },
  {
    id: 'b_steady_sailor',
    name: 'الملاح المنتظم',
    description: 'تحقيق ستريك أسبوع كامل من الدراسة اليومية الجادة.',
    condition: 'ستريك 7 أيام',
    targetValue: 7,
    currentValue: 0,
    unit: 'يوم',
    icon: 'Compass',
    unlocked: false,
    unlockedAt: null,
  },
  {
    id: 'b_wave_crosser',
    name: 'عابر الأمواج',
    description: 'إكمال 25 جلسة تركيز كاملة دون تراجع.',
    condition: 'إكمال 25 جلسة',
    targetValue: 25,
    currentValue: 0,
    unit: 'جلسة',
    icon: 'Ship',
    unlocked: false,
    unlockedAt: null,
  },
  {
    id: 'b_knowledge_trustee',
    name: 'أمين المعرفة',
    description: 'تنويع الحقول المعرفية بالدراسة في 3 مواد مختلفة على الأقل.',
    condition: 'الدراسة في 3 مواد',
    targetValue: 3,
    currentValue: 0,
    unit: 'مادة',
    icon: 'BookOpen',
    unlocked: false,
    unlockedAt: null,
  },
  {
    id: 'b_night_watch',
    name: 'ساهر المرفأ',
    description: 'إكمال جلسة تركيز هادئة في ساعات الليل المتأخرة.',
    condition: 'إكمال جلسة بين 10م و5ص',
    targetValue: 1,
    currentValue: 0,
    unit: 'جلسة',
    icon: 'Moon',
    unlocked: false,
    unlockedAt: null,
  },
  {
    id: 'b_unbroken_path',
    name: 'ثابت المسار',
    description: 'إكمال 7 جلسات متتالية دون انقطاع خارجي أو مغادرة النافذة.',
    condition: '7 جلسات دون انقطاع',
    targetValue: 7,
    currentValue: 0,
    unit: 'جلسة',
    icon: 'ShieldCheck',
    unlocked: false,
    unlockedAt: null,
  },
  {
    id: 'b_captain_rank',
    name: 'ربان الإنجاز',
    description: 'الصعود في سلم المراتب حتى بلوغ رتبة ربان الإنجاز (60 نقطة).',
    condition: 'جمع 60 نقطة تركيز',
    targetValue: 60,
    currentValue: 0,
    unit: 'نقطة',
    icon: 'Award',
    unlocked: false,
    unlockedAt: null,
  },
  {
    id: 'b_mirfa_master',
    name: 'سيد المرفأ',
    description: 'إنجاز 100 ساعة مذاكرة كاملة مسجلة في التطبيق.',
    condition: 'إكمال 100 ساعة (6000 دقيقة)',
    targetValue: 6000,
    currentValue: 0,
    unit: 'دقيقة',
    icon: 'Crown',
    unlocked: false,
    unlockedAt: null,
  },
];

export const INITIAL_QUOTES: QuoteItem[] = [
  {
    id: 'q_1',
    text: 'من صَبَرَ نَالَ، ومَنْ لَزِمَ المرفأَ بلَغَ الساحلَ البعيد.',
    source: 'حكمة عربية',
    isSaved: false,
    isCustom: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'q_2',
    text: 'أحبُّ الأعمالِ إلى اللهِ أدْومُها وإنْ قَلَّ.',
    source: 'حديث شريف',
    isSaved: false,
    isCustom: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'q_3',
    text: 'العلمُ صيدٌ والكتابةُ قيدُه، فقيّدْ صُيودَكَ بالحبالِ الواثِقة.',
    source: 'الإمام الشافعي',
    isSaved: false,
    isCustom: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'q_4',
    text: 'إنَّ النَّفْسَ إذا أُلْزِمَتِ التركيزَ زَكَتْ، وإذا تُركت لِلهَوى تَشتَّتت.',
    source: 'أدب الحكمة',
    isSaved: false,
    isCustom: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'q_5',
    text: 'كلُّ إنجازٍ عظيمٍ كان يومًا فكرةً هادئة تُرعى بالصبر والتكرار.',
    source: 'تأملات المرفأ',
    isSaved: false,
    isCustom: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'q_6',
    text: 'اصبرْ قليلاً فبعدَ العُسْرِ تَيْسِيرُ، وكُلُّ أمرٍ له وَقْتٌ وتَدْبيرُ.',
    source: 'الإمام علي بن أبي طالب',
    isSaved: false,
    isCustom: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'q_7',
    text: 'ليست القوةُ في اندفاعِ البدايات، بل في ثباتِ الرسو والاستمرار.',
    source: 'بحارة الأندلس',
    isSaved: false,
    isCustom: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'q_8',
    text: 'السكينة في العمل العميق مأوى العقل ومستقر الفهم.',
    source: 'أدب الطلب والتحصيل',
    isSaved: false,
    isCustom: false,
    createdAt: new Date().toISOString(),
  },
];

export const INITIAL_SUBJECT: SubjectItem = {
  id: 'sub_default',
  name: 'دراسة عامة',
  color: '#0f766e',
  targetMinutes: 120,
  createdAt: new Date().toISOString(),
};

export const INITIAL_PROFILE: UserProfile = {
  name: 'طالب المرفأ',
  level: 1,
  points: 0,
  streak: 0,
  bestStreak: 0,
  lastStudyDate: null,
};

export const INITIAL_SETTINGS: AppSettings = {
  appearanceMode: 'light',
  oledMode: false,
  theme: 'navy-maritime',
  font: 'Tajawal',
  uiScale: 1,
  timerMode: 'pomodoro',
  focusMinutes: 25,
  shortBreakMinutes: 5,
  longBreakMinutes: 15,
  loops: 4,
  strictMode: false,
  soundEnabled: true,
  vibrationEnabled: true,
  autoStartBreak: false,
  autoStartFocus: false,
  ambientVolume: 0.55,
  personalVolume: 0.35,
  autoUseShield: true,
};

export const INITIAL_DAILY_GOALS: DailyGoalStatus = {
  targetMinutes: 120,
  completedMinutes: 0,
  date: new Date().toISOString().split('T')[0],
};
export const INITIAL_DAILY_GOAL = INITIAL_DAILY_GOALS;

export const INITIAL_STREAK: StreakData = {
  current: 0,
  best: 0,
  shields: 1,
  lastQualifiedDate: null,
  shieldHistory: [],
};

export const INITIAL_LAYOUT: LayoutConfig = {
  preset: 'central',
  widgets: ['quote', 'subject', 'timer', 'daily-progress', 'audio-player'],
};

export const INITIAL_PLANNER: AdaptivePlannerState = {
  weeklyTargetHours: 14,
  availableDays: [0, 1, 2, 3, 4, 5, 6], // All 7 days default
  dailyMaxHours: 4,
  subjectPriorities: [
    { subjectId: 'sub_default', priority: 'medium' }
  ]
};

export const AMBIENT_SOUNDS = [
  { id: 'rain', name: 'المطر الغزير', icon: 'CloudRain', desc: 'إيقاع قطرات المطر الشتوي الهادئ' },
  { id: 'fireplace', name: 'حطب الموقد', icon: 'Flame', desc: 'فرقعة أخشاب الموقد الدافئة' },
  { id: 'waves', name: 'أمواج البحر', icon: 'Waves', desc: 'مد وجزر أمواج رصيف المرفأ' },
  { id: 'whitenoise', name: 'الضوضاء البيضاء', icon: 'Volume2', desc: 'تردد نقي عازل للضجيج المحيط' },
  { id: 'cafe', name: 'أجواء المقهى الهادئ', icon: 'Coffee', desc: 'همهمات خافتة وقرع فناجين بعيد' },
];

export const THEME_PALETTES = [
  {
    id: 'paper-ink',
    name: 'ورق وحبر',
    bgLight: '#fbfbf9',
    cardLight: '#ffffff',
    textLight: '#18181b',
    borderLight: '#e4e4e7',
    primary: '#27272a',
    accent: '#52525b',
    desc: 'مظهر المخطوطات والكتب الأثرية الهادئة',
    preview: { primary: '#27272a', accent: '#52525b', bg: '#fbfbf9' },
  },
  {
    id: 'navy-maritime',
    name: 'كحلي بحري',
    bgLight: '#f8fafc',
    cardLight: '#ffffff',
    textLight: '#0f172a',
    borderLight: '#cbd5e1',
    primary: '#1e3a8a',
    accent: '#0284c7',
    desc: 'عمق المحيط وألوان الموانئ الكلاسيكية',
    preview: { primary: '#1e3a8a', accent: '#0284c7', bg: '#f8fafc' },
  },
  {
    id: 'vintage-olive',
    name: 'زيتوني قديم',
    bgLight: '#fcfdfa',
    cardLight: '#ffffff',
    textLight: '#1b2414',
    borderLight: '#d5ddce',
    primary: '#3a5a40',
    accent: '#588157',
    desc: 'أوراق الشجر العتيقة وهدوء الطبيعة',
    preview: { primary: '#3a5a40', accent: '#588157', bg: '#fcfdfa' },
  },
  {
    id: 'warm-terracotta',
    name: 'طوبي دافئ',
    bgLight: '#fffbf7',
    cardLight: '#ffffff',
    textLight: '#2c1810',
    borderLight: '#ead8cf',
    primary: '#9a3412',
    accent: '#c2410c',
    desc: 'دفء الفخار والصلصال العتيق',
    preview: { primary: '#9a3412', accent: '#c2410c', bg: '#fffbf7' },
  },
  {
    id: 'muted-blue',
    name: 'أزرق باهت',
    bgLight: '#f7fafc',
    cardLight: '#ffffff',
    textLight: '#1a202c',
    borderLight: '#d2dce6',
    primary: '#334155',
    accent: '#64748b',
    desc: 'سماء شتوية باردة تمنح السكينة',
    preview: { primary: '#334155', accent: '#64748b', bg: '#f7fafc' },
  },
  {
    id: 'desert-sand',
    name: 'رملي',
    bgLight: '#fcfaf6',
    cardLight: '#ffffff',
    textLight: '#2d241e',
    borderLight: '#e7ded4',
    primary: '#78593a',
    accent: '#a07855',
    desc: 'حبيبات الرمال الذهبية وسكينة الصحراء',
    preview: { primary: '#78593a', accent: '#a07855', bg: '#fcfaf6' },
  },
  {
    id: 'library-green',
    name: 'أخضر مكتبي',
    bgLight: '#f7faf8',
    cardLight: '#ffffff',
    textLight: '#112217',
    borderLight: '#cde0d4',
    primary: '#164e3f',
    accent: '#0f766e',
    desc: 'أجواء خزائن الكتب الكبرى ومصابيح القراءة',
    preview: { primary: '#164e3f', accent: '#0f766e', bg: '#f7faf8' },
  },
  {
    id: 'archival-violet',
    name: 'بنفسجي أرشيفي',
    bgLight: '#faf8fc',
    cardLight: '#ffffff',
    textLight: '#251532',
    borderLight: '#ded6e8',
    primary: '#581c87',
    accent: '#7e22ce',
    desc: 'أروقة المخطوطات والوثائق الملكية',
    preview: { primary: '#581c87', accent: '#7e22ce', bg: '#faf8fc' },
  },
  {
    id: 'classic-grey',
    name: 'رمادي كلاسيكي',
    bgLight: '#f9fafb',
    cardLight: '#ffffff',
    textLight: '#111827',
    borderLight: '#d1d5db',
    primary: '#374151',
    accent: '#4b5563',
    desc: 'حياد تام وتوازن بصري بدون تشتيت',
    preview: { primary: '#374151', accent: '#4b5563', bg: '#f9fafb' },
  },
];
